services:
  - type: web
    name: text-recognition
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn ocr_basic:app --preload"
    plan: free
    region: frankfurt
