services:
  - type: web
    name: ocr-app
    env: python
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y tesseract-ocr
      pip install -r requirements.txt
    startCommand: gunicorn app:app
